### ISSUE TITLE
Search bar for fonts

### ISSUE THREAD

**Issue by AmeyaAdam** [vishwajeetraj11/osresume#1]
Adding a search bar to the font tab & if possible sort the fonts in the most-used or professional looking at top.

**Comment by vishwajeetraj11** [comment]
Sure, will look forward to adding a search bar. Although implementing popular fonts will probably take time because there is no such metric in json.

**Comment by vishwajeetraj11** [comment]
Hi, Font Search is implemented. You can check that out.
