### ISSUE TITLE
unhandled runtiem error

### ISSUE THREAD

**Issue by SarbastJundi** [vishwajeetraj11/osresume#6]
Unhandled Runtime Error
Error: ClerkJS: Token has expired (exp='1641579042').

Call Stack
<unknown>
https://clerk.pbda0.dh1rh.lcl.dev/npm/@clerk/clerk-js@1/dist/clerk.browser.js (2:20186)
<unknown>
https://clerk.pbda0.dh1rh.lcl.dev/npm/@clerk/clerk-js@1/dist/clerk.browser.js (2:20249)

**Comment by vishwajeetraj11** [comment]
Please try again, i've updated the project to next.js 13 and updated clerk to latest version.

**Comment by vishwajeetraj11** [comment]
Closing this.
