### ISSUE TITLE
Print Breaks

### ISSUE THREAD

**Issue by gautam-jha** [vishwajeetraj11/osresume#7]
Hello,

I tried to use the application it was really a very beautiful job done designing these templates.
but the issue I faced in the application is the 2nd page is not supported.

I am unable to set it up in my local for some reason. but I looked into the code, the problem seems like the use of flex or something small. 

https://stackoverflow.com/questions/59193584/how-can-i-use-page-break-in-react-to-print

Please do let me know If you're planning to update it or some help or guidance so I can do it.

Tested Browsers: Chrome, Firefox
OS: Ubuntu

Screenshots:
I have 4 items at work.
![image](https://user-images.githubusercontent.com/16630278/153060685-eb28ef74-42aa-4bb1-bc88-0039f2ed5594.png)

Not able to scroll to more than that as the parent has `overflow-hidden` class added in it.
![image](https://user-images.githubusercontent.com/16630278/153060921-b9fbca12-1f40-4200-b85a-e77dd1990fbf.png)

On the print page, there is only 1 page, suppose to be more than 1 page.
![image](https://user-images.githubusercontent.com/16630278/153061617-227a568f-2d2b-44d2-9c92-4857cab81648.png)

**Comment by vishwajeetraj11** [comment]
Please attach relevant screenshots.

**Comment by gautam-jha** [comment]
@vishwajeetraj11 added.

**Comment by vishwajeetraj11** [comment]
Hey, currently I don't support this. 
I primarily built this project for 1 paged resume. (and it's also not recommended to have a resume of more than 1 page).
So, I can't really be working on that. 
But what i can do is help you setup a local development environment where you can play around with the implementation.

**Comment by vishwajeetraj11** [comment]
Closing this
