### ISSUE TITLE
🚀 Great progress, please keep building on!

### ISSUE THREAD

**Issue by amruthpillai** [vishwajeetraj11/osresume#9]
Hey there!

Your repository was just recommended to me on the homepage. I maintain a similar open-source resume builder project, so I kind of understand the troubles that come with it. You've really done some great work on the project, keeping true to its name "over-simplified" that the code was so neatly organized and understandable.

Please keep improving on it further, looking forward to seeing what you build! :)

**Comment by vishwajeetraj11** [comment]
Hey @AmruthPillai,
Thanks, I've checked your resume builder its really good. 
The project is aimed at simplifying the resume-building process for everyone.
I'm constantly looking for ways to enhance and refine the project further.
